# Generated by Django 3.1.3 on 2021-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joboffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=150)),
                ('salary', models.PositiveIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
